/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TestRender {
    }
    interface TestingProps {
        "first": string;
        "last": string;
    }
}
declare global {
    interface HTMLTestRenderElement extends Components.TestRender, HTMLStencilElement {
    }
    var HTMLTestRenderElement: {
        prototype: HTMLTestRenderElement;
        new (): HTMLTestRenderElement;
    };
    interface HTMLTestingPropsElement extends Components.TestingProps, HTMLStencilElement {
    }
    var HTMLTestingPropsElement: {
        prototype: HTMLTestingPropsElement;
        new (): HTMLTestingPropsElement;
    };
    interface HTMLElementTagNameMap {
        "test-render": HTMLTestRenderElement;
        "testing-props": HTMLTestingPropsElement;
    }
}
declare namespace LocalJSX {
    interface TestRender {
    }
    interface TestingProps {
        "first"?: string;
        "last"?: string;
    }
    interface IntrinsicElements {
        "test-render": TestRender;
        "testing-props": TestingProps;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "test-render": LocalJSX.TestRender & JSXBase.HTMLAttributes<HTMLTestRenderElement>;
            "testing-props": LocalJSX.TestingProps & JSXBase.HTMLAttributes<HTMLTestingPropsElement>;
        }
    }
}
