/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComplexProp {
        /**
          * Values prop
         */
        "values": Array<string>;
    }
    interface MyInstance {
        /**
          * prop lastName
         */
        "lastName": string;
        /**
          * prop name
         */
        "name": string;
    }
}
declare global {
    interface HTMLMyComplexPropElement extends Components.MyComplexProp, HTMLStencilElement {
    }
    var HTMLMyComplexPropElement: {
        prototype: HTMLMyComplexPropElement;
        new (): HTMLMyComplexPropElement;
    };
    interface HTMLMyInstanceElement extends Components.MyInstance, HTMLStencilElement {
    }
    var HTMLMyInstanceElement: {
        prototype: HTMLMyInstanceElement;
        new (): HTMLMyInstanceElement;
    };
    interface HTMLElementTagNameMap {
        "my-complex-prop": HTMLMyComplexPropElement;
        "my-instance": HTMLMyInstanceElement;
    }
}
declare namespace LocalJSX {
    interface MyComplexProp {
        /**
          * Values prop
         */
        "values"?: Array<string>;
    }
    interface MyInstance {
        /**
          * prop lastName
         */
        "lastName"?: string;
        /**
          * prop name
         */
        "name"?: string;
    }
    interface IntrinsicElements {
        "my-complex-prop": MyComplexProp;
        "my-instance": MyInstance;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-complex-prop": LocalJSX.MyComplexProp & JSXBase.HTMLAttributes<HTMLMyComplexPropElement>;
            "my-instance": LocalJSX.MyInstance & JSXBase.HTMLAttributes<HTMLMyInstanceElement>;
        }
    }
}
